image: python:3.6-alpine

before_script:
  - pip install markdown
  - pip install mkdocs
  - pip install mkdocs-minify-plugin
  - pip install mkdocs-material
  - pip install mkdocs-redirects

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
