image: python:alpine

before_script:
  - bash /builds/MadeByThePinsTeam-DevLabs/legal/legal.madebythepins.tk/command-prompt/deploy-docs.sh

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master