site_name: Legal Site by the Pins
site_url: https://legal.madebythepins.tk
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
    - Home: ../
    - 'Legal Stuff': 
        - 'Privacy Policy':
            - 'Legal Text': privacy/full-privacy-policy
            - 'Human-readable version': privacy/summary-of-privacy-policy
        - 'Terms of Service': tos
    - 'Transparency':
        - 'Transparency Reports Homepage': transparency
        - 'Takedowns and Censorship': transparency/takedowns-and-censorship
use_directory_urls: true
plugins:
    - search
    - redirects:
        redirect_maps:
            'privacy-policy': 'privacy/full-priacy-policy'
            'changelogs': 'about/changelogs'
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"