site_name: Legal Site by the Pins
site_url: https://legal.madebythepins.tk

# theme
theme: material

# navigation
nav:
    - Home: ./
    - 'Legal Stuff': 
        - 'General Privacy Policy':
            - 'Legal Text': privacy-policy/legalese
            - 'Human-readable version': privacy-policy/human
        - 'General Terms of Service':
            - 'Legal Text': 'tos/legalese'
            - 'Human-readable version': 'tos/human'
        - 'Accounts IAM/SSO':
            - 'Privacy Policy': iam/privacy
            - 'Terms of Service': iam/tos
    - 'Transparency Reports':
        - 'Transparency Reports Homepage': transparency
        - 'Intellectual Property Takedowns': transparency/reports/ip-takedowns
        - 'Reported Content': transparency/reports/reported-content
        - 'Takedowns due to Censorship': transparency/reports/censorship-takedowns
        - 'Data Requests': transparency/reports/data-request
        - 'ToS / Code of Conduct Violations': transparency/reports/violations
        - 'Other Reports': transparency/reports/other-reports

use_directory_urls: true

plugins:
    - search
    - redirects:
        redirect_maps:
            'privacy-policy': privacy/policy
            'transparency/reports': transparency
            'transparency/ip-takeodwns': transparency/reports/ip-takedowns
            'transparency/reported-content': transparency/reports/reported-content
            'transparency/censorship-takedowns': transparency/reports/censorship-takedowns
            'transparency/data-requests': transparency/reports/data-requests
            'transparency/violations': transparency/reports/violations
            'transparency/other-reports': transparency/reports/other-reports

# links
repo_url: https://gitlab.com/MadeByThePinsTeam-DevLabs/legal/legal.madebythepins.tk
edit_uri: blob/master/docs/
# extensions TODO
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"
