site_name: Legal Site by the Pins
site_url: https://legal.madebythepins.tk
theme: material
nav:
    - Home: ../
    - 'Legal Stuff': 
        - 'General Privacy Policy':
            - 'Legal Text': privacy/policy
            - 'Human-readable version': privacy/policy/summary
        - 'General Terms of Service': tos
        - 'Accounts IAM':
            - 'Privacy Policy': iam/privacy
            - 'Terms of Service': iam/tos
    - 'Transparency':
        - 'Transparency Reports Homepage': transparency
        - 'Takedowns and Censorship': transparency/takedowns-and-censorship
use_directory_urls: true
plugins:
    - search
    - redirects:
        redirect_maps:
            'privacy-policy': 'privacy/full-priacy-policy'
            'changelogs': 'about/changelogs'
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"