# Basic site config
site_name: Legal Site by the Pins
site_description: 'The one-stop place for reading our fine prints.'
site_url: https://legal.madebythepins.tk

# Themes and font config
theme:
     name: material
     # Avoid Google's GDPR issues
     font: false
     palette:
       # Enable dark mode by default
       scheme: slate

# Navigation
nav:
    - Home: ./
    - 'Legal Stuff': 
        - 'General Privacy Policy':
            - 'Legal Text': privacy-policy/legalese
            - 'Human-readable version': privacy-policy/human
        - 'General Terms of Service':
            - 'Legal Text': 'tos/legalese'
            - 'Human-readable version': 'tos/human'
        - 'Accounts IAM/SSO':
            - 'Privacy Policy': iam/privacy
            - 'Terms of Service': iam/tos
    - 'Transparency Reports':
        - 'Transparency Reports Homepage': transparency
        - 'Intellectual Property Takedowns': transparency/reports/ip-takedowns
        - 'Reported Content': transparency/reports/reported-content
        - 'Takedowns due to Censorship': transparency/reports/censorship-takedowns
        - 'Data Requests': transparency/reports/data-request
        - 'ToS / Code of Conduct Violations': transparency/reports/violations
        - 'Other Reports': transparency/reports/other-reports

use_directory_urls: true

plugins:
    - search
    - minify:
        minify_html: true
    - redirects:
        redirect_maps:
            # For redirect maps, you should be like this:
            # ==========================================
            # 'old/dir/to/article': new/dir/to/article
            # ==========================================
            # Copy the example after # and an space to the last entity. Press Enter
            # or Return and paste the example. Don't forget to customize it first before
            # you save, commit and push.
            'privacy-policy': your-privacy/privacy-policy
            'transparency/reports': transparency
            'transparency/ip-takeodwns': transparency/reports/ip-takedowns
            'transparency/reported-content': transparency/reports/reported-content
            'transparency/censorship-takedowns': transparency/reports/censorship-takedowns
            'transparency/data-requests': transparency/reports/data-requests
            'transparency/violations': transparency/reports/violations
            'transparency/other-reports': transparency/reports/other-reports

# links
repo_url: https://gitlab.com/MadeByThePinsHub/legal/legal.madebythepins.tk
edit_uri: blob/main/legal-code
# extensions TODO
markdown_extensions:
    - admonition
    - toc:
        permalink: "#"
        separator: "_"

# Any customizations should be placed here.
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: fontawesome/brands/github-alt
      link: https://github.com/MadeByThePinsHub
    - type: fontawesome/brands/twitter
      link: https://twitter.com/thepinsteam
    - type: fontawesome/brands/gitlab
      link: https://gitlab.com/MadeByThePinsTeam-DevLabs

# Documentation files
docs_dir: legal-code
